In [2]:
import numpy as np

x = np.arange(1,11)

print(x)
print(np.sum(x))
print(np.mean(x))
print(np.std(x))



[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
2.8722813232690143


In [8]:
#2

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1])
print(arr[3])
print(arr[2:])

20
40
[30 40 50 60]


In [9]:
#3

import numpy as np
x = np.arange(1,13)
print(x)
print(x.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#4

import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])
print(A)
print(B)

print(np.add(A,B))
print(np.subtract(B,A))
print(np.multiply(A,B))
print(np.divide(A,B))

[1 2 3]
[4 5 6]
[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
